### ISSUE TITLE
doesn't work correctly with new upcoming flac  1.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bleskodev/rubyripper#568]
```
1) Please describe the steps to reproduce the situation:
a.build & install latest flac, currently 1.3.0pre4
b.use RR to rip & encode a track to flac
c.

2) What is the expected output? What do you see instead?
Expected to produce a flac file
What happens is only a small flac file is produced, around 78kB here. Has 
headers & tags but no content

3) What version of rubyripper are you using? On what operating system? The
gtk2 of commandline interface?
Using current git as of 05/12 ( Rubyripper 0.7.0a1

4) Is this not already fixed with the latest & greatest code? See for
instructions the Source tab above.

5) Does the problem happen with all discs? If not, please attach
the output of cdparanoia -Q with a disc that gives trouble.
All

6) Please explain why this change is important for you. Also, how many
users would benefit from this change?
Will be releasing soon & eventually on various distros

Please provide any additional information below. The more useful
information provided, the sooner the issue will be fixed.

Sample encode attached

Note on flac build - tried with both static & shared build of flac 1.3.0pre4, 
same results
New flac works fine with abcde, ect.

Note that ruby versions older than 1.9 are no longer supported. You are
advised to upgrade instead.

```

Original issue reported on code.google.com by `mc631man` on 12 May 2013 at 5:50

Attachments:
- [01 - Who Do You Love.flac](https://storage.googleapis.com/google-code-attachments/rubyripper/issue-568/comment-0/01 - Who Do You Love.flac)

**Comment by ACOdell** [comment]
More of a heads up than anything.

I just used this on Debian Jessie and I encountered the same problem (using the stable branch). Luckily, the quick fix from 3 years ago still worked after I edited the source file.

**Comment by bleskodev** [comment]
Hello, I'm using flac 1.3.1 with master branch without problems. I do not currently recommend using stable branch with this fork because the stable branch is very old (around 4 years). The code was abandoned several years ago and I have made a number of fixes on the main branch.

If you have time and energy, please test the latest version on the main branch and confirm that the bug is fixed (this would give me an excuse to close this issue as fixed; I would have an external confirmation that this works...)

**Comment by olehj** [comment]
I just cloned the git and use flac 1.3.1. I ripped a song to flac successfully.

**Comment by doc75** [comment]
Working fine with flac 1.3.1 and ruby 1.9.

**Comment by bleskodev** [comment]
Closed because it seems the problem has been fixed in the latest version.
