### ISSUE TITLE
configure needs to be updated to version 0.7.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bleskodev/rubyripper#570]
```
configure needs to be updated to version 0.7.0

Trying to use attached spec file on fedora 19


```

Original issue reported on code.google.com by `simon.lewis@slnet-online.de` on 30 May 2013 at 7:58

Attachments:
- [rubyripper.spec](https://storage.googleapis.com/google-code-attachments/rubyripper/issue-570/comment-0/rubyripper.spec)

**Comment by bleskodev** [comment]
Fixed.
