### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by baldurmen** [bleskodev/rubyripper#596]
Hey!

Thanks for the bug fixes you have done! I've been thinking of packaging this for Debian for a while now and I hope to have some time to do it this summer.

Could you make a release with 0.7 ?

**Comment by bleskodev** [comment]
Hey, no problem.
I still need to study the release process. Currently it is blocked in the configure script saying that this is an alpha release and the script needs to be adapted for the final release.
In addition, the original author kept a list of bugs he wanted to fix for the final 0.7 release (see issue #556) so I don't know what to do with them (I'm just a simple rubyripper user who got tired of some obvious bugs in the latest available code and decided to fix them).
BTW, thanks for your work on README file!

**Comment by alexminder** [comment]
You may make release 0.6.80

**Comment by bleskodev** [comment]
Fixed configure script. Tagged 0.7.0rc1 release. Updated stable branch.
Closing this issue.
