### ISSUE TITLE
musicbrainz denies user-agent 'Ruby'

### ISSUE THREAD

**Issue by Safari77** [bleskodev/rubyripper#599]
I get 403 error. If I change user-agent to Firefox, it works.

**Comment by bleskodev** [comment]
Thanks for reporting the bug!
I should be fixed (in my tests, I do not get rejected by Musicbrainz server). Can you confirm it works for you?
Thanks.

**Comment by bleskodev** [comment]
With no feedback, I'm supposing the bug has been fixed and I'm closing the issue.
