### ISSUE TITLE
underscores in file names

### ISSUE THREAD

**Issue by Safari77** [bleskodev/rubyripper#601]
```
[X] Replace spaces with underscores in file names
```

That's neat, it works, but also replaces spaces with underscores in the **TAGS**!

**Comment by bleskodev** [comment]
Thanks for reporting this. Do you have a concrete example or more details when/where this happens?
Thanks.

**Comment by bleskodev** [comment]
Should be fixed now. Please confirm. Thanks.

**Comment by Safari77** [comment]
Works now. Thanks again.
