### ISSUE TITLE
ruby-gtk2 issue

### ISSUE THREAD

**Issue by thwaller** [bleskodev/rubyripper#610]
When I attempt to run rrip_gui, I get the following output:
> The ruby-gtk2 library could not be found. Is it installed?

When I check this package, I get the following:
> ruby-gtk2 is already the newest version (3.1.8-6ubuntu1).

I am running Ubuntu 17.10, all updates up to date on a weekly basis at a minimum.

**Comment by bleskodev** [comment]
Hi, sorry for the late reply,
It looks some other people might have the same problem...

Can you try this solution?
https://askubuntu.com/questions/984648/location-of-ruby-gtk2-library-files-moved-in-17-10

I will try to improve the code in question to display the original failure message in order to help diagnosing the problem in the future.

**Comment by thwaller** [comment]
Thanks for the reply. I have checked on this today and found it is working now. I read the link you provided and have found that the package ruby-cairo-gobject is installed, so I am thinking that maybe in the last month it was installed, thus resolving the problem. I do not recall installing it, but I did a lot of software updates, installs and changes for audio encoders and analyzers and similar.

For me this is closed, but I will leave open for your closure decision as you have added a self assignment.

**Comment by tukusejssirs** [comment]
I can confirm that installing `ruby-cairo-gobject` solved / worked around this issue.

Btw, before installating `ruby-cairo-gobject`, this was the output of the `./configure`:
```bash
$ ./configure --enable-lang=en,sk --enable-gtk2 --enable-cli --prefix=/usr


CHECKING FORCED DEPENDENCIES

cdparanoia: [OK]

CHECKING OPTIONAL DEPENDENCIES

ruby-gtk2: [NOT OK]
You won't be able to use the gtk2 interface.
ruby-gettext: [OK]
discid: [OK]
cd-discid: [OK]
eject: [OK]
flac: [OK]
vorbis: [OK]
lame: [OK]
wavegain: [NOT OK]
You won't be able to replaygain WAVE files.
vorbisgain: [OK]
mp3gain: [NOT OK]
You won't be able to replaygain LAME mp3 files.
normalize: [NOT OK]
You won't be able to normalize audio files.
cdrdao: [OK]
cd-info: [NOT OK]
Cd-info helps to detect data tracks.
ls: [OK]
diskutil: [NOT OK]


Creating the Makefile...
A summary of your settings:

Using the following locations for install:
* Executables: /usr/bin
* Localization files: /usr/share/locale
* Icon file: /usr/share/icons/hicolor/128x128/apps
* Desktop file: /usr/share/applications
* Library files: /usr/lib/rubyripper

Gtk2 frontend will be installed
Cli frontend will be installed

You can now run make install
Make sure you've got the writing privileges
```

And after installing it:

```bash
$ ./configure --enable-lang=en,sk --enable-gtk2 --enable-cli --prefix=/usr


CHECKING FORCED DEPENDENCIES

cdparanoia: [OK]

CHECKING OPTIONAL DEPENDENCIES

ruby-gtk2: [OK]
ruby-gettext: [OK]
discid: [OK]
cd-discid: [OK]
eject: [OK]
flac: [OK]
vorbis: [OK]
lame: [OK]
wavegain: [NOT OK]
You won't be able to replaygain WAVE files.
vorbisgain: [OK]
mp3gain: [NOT OK]
You won't be able to replaygain LAME mp3 files.
normalize: [NOT OK]
You won't be able to normalize audio files.
cdrdao: [OK]
cd-info: [NOT OK]
Cd-info helps to detect data tracks.
ls: [OK]
diskutil: [NOT OK]


Creating the Makefile...
A summary of your settings:

Using the following locations for install:
* Executables: /usr/bin
* Localization files: /usr/share/locale
* Icon file: /usr/share/icons/hicolor/128x128/apps
* Desktop file: /usr/share/applications
* Library files: /usr/lib/rubyripper

Gtk2 frontend will be installed
Cli frontend will be installed

You can now run make install
Make sure you've got the writing privileges
```

System info:
```bash
$ uname -a
Linux lnv-e530c 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -d
Description:	Ubuntu 17.10
```

**Comment by tukusejssirs** [comment]
But still, I could not install `rubyripper` successfully. See the output in [rubyripper_make_install_output.txt](https://github.com/bleskodev/rubyripper/files/1879330/rubyripper_make_install_output.txt).

**Comment by tukusejssirs** [comment]
But still, I could not install `rubyripper` successfully. See the output in [rubyripper_make_install_output.txt](https://github.com/bleskodev/rubyripper/files/1879330/rubyripper_make_install_output.txt).

**Comment by thwaller** [comment]
@tukusejssirs - that looks like the issue is not using sudo prior to make install.

So you should run:
`$ sudo make install`

Also, most of your [NOT OK] items are expected, all except cd-info. You will want to install that package. The normalizing packages have changed some, and I assume the dev needs to update some things to accommodate. For me though, I do not normalize, ever, when ripping, so it is no matter to me... but would be nice to see OK.

**Comment by tukusejssirs** [comment]
Well, then I did it with and without `sudo`, too, but none of them worked (at least seamingly).

And I understood it well what `[NOT OK]` meant. The list programs are just optional dependencies. ;)

Still, I’ve just run `make clean && ./configure --enable-lang=en --enable-gtk2 --enable-cli --prefix=/usr && sudo make install` and it worked. Thanks. :)
