### ISSUE TITLE
Crash in the absence of connection to the Internet

### ISSUE THREAD

**Issue by nafanz** [bleskodev/rubyripper#617]
Ubuntu 18.04.1 LTS
Rubyripper version 0.7.0rc2

When you run an application with the Internet turned off, crash occurs
The disc is inserted into the drive at this moment

`nafanz@nafanz-desktop:~$ rrip_gui
Gtk-Message: 20:55:59.397: Failed to load module "canberra-gtk-module"
DEBUG: cdparanoia -d /dev/sr1 -vQ
DEBUG: discid or cd-discid isn't found on your system!
DEBUG: Using fallback...
DEBUG: CGI query: http://freedb.freedb.org/~cddb/cddb.cgi?cmd=cddb+query+630D0508+8+150+7063+42433+85982+118352+161252+175052+188833+3335&hello=anonymous+my_secret.com+rubyripper+0.7.0rc2&proto=6
DEBUG: Freedb connection error: Failed to open TCP connection to freedb.freedb.org:80 (getaddrinfo: Неизвестное имя или служба)
DEBUG: CGI query: https://musicbrainz.org/ws/2/discid/DVf3KOQ0M99pDLru7K8m0b8T_6M-?toc=1+8+250125+150+7063+42433+85982+118352+161252+175052+188833&inc=artists+recordings+artist-credits+release-groups
#<Thread:0x00005594daf7fd90@/usr/bin/rrip_gui:140 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	21: from /usr/bin/rrip_gui:146:in `block in scanDisc'
	20: from /usr/lib/rubyripper/gtk2/gtkDisc.rb:37:in `start'
	19: from /usr/lib/rubyripper/gtk2/gtkDisc.rb:44:in `refresh'
	18: from /usr/lib/rubyripper/disc/disc.rb:40:in `scan'
	17: from /usr/lib/rubyripper/disc/disc.rb:106:in `setMetadata'
	16: from /usr/lib/rubyripper/metadata/main.rb:35:in `get'
	15: from /usr/lib/rubyripper/metadata/main.rb:35:in `each'
	14: from /usr/lib/rubyripper/metadata/main.rb:36:in `block in get'
	13: from /usr/lib/rubyripper/metadata/main.rb:54:in `startup'
	12: from /usr/lib/rubyripper/metadata/main.rb:63:in `musicbrainz'
	11: from /usr/lib/rubyripper/metadata/musicbrainz.rb:41:in `get'
	10: from /usr/lib/rubyripper/metadata/musicbrainz/getMusicBrainzRelease.rb:45:in `queryDisc'
	 9: from /usr/lib/rubyripper/metadata/musicbrainz/getMusicBrainzRelease.rb:98:in `queryMusicBrainzForMatches'
	 8: from /usr/lib/rubyripper/system/network.rb:46:in `get'
	 7: from /usr/lib/ruby/2.5.0/net/http.rb:1455:in `request'
	 6: from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
	 5: from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	 4: from /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
	 3: from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
	 2: from /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	 1: from /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
/usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': Failed to open TCP connection to musicbrainz.org:443 (getaddrinfo: Неизвестное имя или служба) (SocketError)
Traceback (most recent call last):
	21: from /usr/bin/rrip_gui:146:in `block in scanDisc'
	20: from /usr/lib/rubyripper/gtk2/gtkDisc.rb:37:in `start'
	19: from /usr/lib/rubyripper/gtk2/gtkDisc.rb:44:in `refresh'
	18: from /usr/lib/rubyripper/disc/disc.rb:40:in `scan'
	17: from /usr/lib/rubyripper/disc/disc.rb:106:in `setMetadata'
	16: from /usr/lib/rubyripper/metadata/main.rb:35:in `get'
	15: from /usr/lib/rubyripper/metadata/main.rb:35:in `each'
	14: from /usr/lib/rubyripper/metadata/main.rb:36:in `block in get'
	13: from /usr/lib/rubyripper/metadata/main.rb:54:in `startup'
	12: from /usr/lib/rubyripper/metadata/main.rb:63:in `musicbrainz'
	11: from /usr/lib/rubyripper/metadata/musicbrainz.rb:41:in `get'
	10: from /usr/lib/rubyripper/metadata/musicbrainz/getMusicBrainzRelease.rb:45:in `queryDisc'
	 9: from /usr/lib/rubyripper/metadata/musicbrainz/getMusicBrainzRelease.rb:98:in `queryMusicBrainzForMatches'
	 8: from /usr/lib/rubyripper/system/network.rb:46:in `get'
	 7: from /usr/lib/ruby/2.5.0/net/http.rb:1455:in `request'
	 6: from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
	 5: from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	 4: from /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
	 3: from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
	 2: from /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	 1: from /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
/usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': Failed to open TCP connection to musicbrainz.org:443 (getaddrinfo: Неизвестное имя или служба) (SocketError)`

**Comment by bleskodev** [comment]
Hi, interesting bug, thanks for reporting. I'll have a look and try to capture this error.
