### ISSUE TITLE
Error - Edit the track info

### ISSUE THREAD

**Issue by elmitico** [bleskodev/rubyripper#622]
Hello.

When Iam editing the track info, the following error appears (in Void Linux):

*** EDIT TRACK INFO ***

 1) Suite nº1 - Obertura
 2) Courante
 3) Gavote
 4) Forlane
 5) Minueto
 6) Bourree
 7) Passepied
 8) Suite nº2 - Obertura
 9) Rondo
10) Sarabanda
11) Track 11
12) Track 12
13) Track 13
14) Track 14
99) Back to metadata menu

Please type the number of the data you wish to change [99] : Bourree
Traceback (most recent call last):
        26: from /usr/bin/rrip_cli:187:in `<main>'
        25: from /usr/bin/rrip_cli:54:in `start'
        24: from /usr/bin/rrip_cli:123:in `loopMainMenu'
        23: from /usr/bin/rrip_cli:123:in `loopMainMenu'
        22: from /usr/bin/rrip_cli:123:in `loopMainMenu'
        21: from /usr/bin/rrip_cli:117:in `loopMainMenu'
        20: from /usr/lib/rubyripper/cli/cliDisc.rb:49:in `changeMetadata'
        19: from /usr/lib/rubyripper/cli/cliDisc.rb:133:in `loopMainMenu'
        18: from /usr/lib/rubyripper/cli/cliDisc.rb:164:in `loopSubMenuDisc'
        17: from /usr/lib/rubyripper/cli/cliDisc.rb:164:in `loopSubMenuDisc'
        16: from /usr/lib/rubyripper/cli/cliDisc.rb:164:in `loopSubMenuDisc'
        15: from /usr/lib/rubyripper/cli/cliDisc.rb:160:in `loopSubMenuDisc'
        14: from /usr/lib/rubyripper/cli/cliDisc.rb:134:in `loopMainMenu'
        13: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
        12: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
        11: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
        10: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
         9: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
         8: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
         7: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
         6: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
         5: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
         4: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
         3: from /usr/lib/rubyripper/cli/cliDisc.rb:194:in `loopSubMenuTracks'
         2: from /usr/lib/rubyripper/cli/cliDisc.rb:182:in `loopSubMenuTracks'
         1: from /usr/lib/rubyripper/cli/cliDisc.rb:178:in `showSubMenuTracks'
/usr/lib/rubyripper/cli/cliGetAnswer.rb:79:in `get': undefined method `print_' for #<IO:<STDOUT>> (NoMethodError)
Did you mean?  print
               printf

**Comment by bleskodev** [comment]
Hi, thanks for reporting this.
With the above commit, I believe this problem should be fixed.
Please, reopen the bug with more info in case it isn't.
Thanks!
