### ISSUE TITLE
Danish update

### ISSUE THREAD

**Issue by Joedalton2** [bleskodev/rubyripper#623]
da
joe@debianbuster:~/over/andet/rubyripper$ msgfmt --statistics -c -v -o /dev/null rubyripper.po
rubyripper.po: 378 oversatte tekster.
Hi an update for Danish
[rubyripper.po.tar.gz](https://github.com/bleskodev/rubyripper/files/2715663/rubyripper.po.tar.gz)
bye
Joe

**Comment by bleskodev** [comment]
Merged (sorry for the delay), thanks a lot!
