### ISSUE TITLE
Include Musicbrainz Disc ID in .cue or .log file.

### ISSUE THREAD

**Issue by carlu78** [bleskodev/rubyripper#626]
The title in a nutshell. For the purposes of managing metadata progammatically, it would be nice having a file in each disc folder with the calculated Musicbrainz ID. As the Musicbrainz database gets corrected or updated, a relatively simple script could use the disc ID to apply changes with or without human guidance. Currently the FreeDB ID is written to the Cue Sheet, though I think the ripping log would be just as good, as long as it is properly labelled. 

I expect this to be a low priority enhancement, but I think it should be a simple change. If I knew anything about Ruby, I would take a crack at it myself.

Edit: After poking through some output FLAC files again, it appears that the FreeDB ID is written to each file's metadata. Perhaps if Musicbrainz is selected as the metadata resource, the Musicbrainz ID could be written to this field instead. This would be at least as good as writing it to the .cue or .log file, and probably better.

**Comment by bleskodev** [comment]
Hi, sorry for the long delay concerning this issue.
If you are still interested, I have added MUSICBRAINZ_DISCID into .cue file. Please check if this is what you expected.
Thanks!
