### ISSUE TITLE
[Arch Linux] 0.8 configure can't find ruby-gtk3 

### ISSUE THREAD

**Issue by mokkurkalve** [bleskodev/rubyripper#629]
I'm trying to update Arch Linux rubyripper to v0.8.0rc1. But I cannot make rrip_gui work, as rubyrippers configure or rrip_gui can't find the installed ruby-gtk3. I did install ruby-gtk3 from Arch repository beforehand, this package:
https://archlinux.org/packages/community/x86_64/ruby-gtk3/
And as I don't know much about Ruby I am at a loss where to go from here. Any pointers how to debug this?

**Comment by bleskodev** [comment]
Hi, yes, I believe this is the known problem with Arch Linux.
See the bug #627 (closed) for the solution.
Tell me if this helps or additional problems exist.

**Comment by bleskodev** [comment]
I have reported the packaging bug to Arch: https://bugs.archlinux.org/task/69948
I hope they will be able to fix it and correctly package ruby-cairo gem.

**Comment by mokkurkalve** [comment]
I'll wait a couple of days to see whether the ruby-cairo packaging bug gets fixed on the Arch Linux end then.

**Comment by mokkurkalve** [comment]
I can confirm that v0.8.0rc1 rrip_gui works when ruby-native-package-installer and red-colors gems  are installed.
However, I cannot update the rubyripper in AUR until the ruby-cairo package are fixed in Arch Linux....

**Comment by mokkurkalve** [comment]
The packaging bug in Arch Linux ruby-cairo are fixed and all is well. This bug can be closed.
