### ISSUE TITLE
Replaygain?

### ISSUE THREAD

**Issue by mokkurkalve** [bleskodev/rubyripper#630]
Using rrip_gui v0.8.0rc1 (on Arch) I rip to both Ogg Vorbis and Wavpack. I also set "Use replaygain on audio files" to "Album / Audiophile modus". 
However, no replaygain tags are added to the files. I have both wvgain and vorbisgain in $PATH.

**Comment by bleskodev** [comment]
Hi, I must admit I have never tested this part. I'll have a look what is happening. 
From the code, I see that support for replaygain in Wavpack is not implemented, so I would say it is normal that it does not work. 
Vorbis is implemented so I would expect that it works, but I'll check it out.

**Comment by bleskodev** [comment]
I have pushed two commits which should fix both issues (replaygain not working in album mode and replaygain not working at all for wavpack encoder). If you could confirm the fixes, it would be great!

**Comment by mokkurkalve** [comment]
It seems this works all OK.  :-)
Thanks!


søn. 21. mar. 2021 kl. 12:45 skrev bleskodev ***@***.***>:
>
> I have pushed two commits which should fix both issues (replaygain not working in album mode and replaygain not working at all for wavpack encoder). If you could confirm the fixes, it would be great!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 



Eivind Eide

"ONLY THOSE WHO ATTEMPT THE IMPOSSIBLE WILL ACHIEVE THE ABSURD"
- Oceania Association of Autonomous Astronauts
