### ISSUE TITLE
Crashed when trying to add replay gain for Opus encodes

### ISSUE THREAD

**Issue by FoilBlue** [bleskodev/rubyripper#631]
wavegain dep was missing btw. 
```
$ rrip_gui 
/usr/local/lib/rubyripper/secureRip.rb:335: warning: constant ::Fixnum is deprecated
WARNING: No replaygain available for opus.
#<Thread:0x00007f1afcdc7f80 /usr/local/lib/rubyripper/encode.rb:85 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	2: from /usr/local/lib/rubyripper/encode.rb:86:in `block (2 levels) in startEncoding'
	1: from /usr/local/lib/rubyripper/encode.rb:153:in `encodeTrack'
/usr/local/lib/rubyripper/codecs/main.rb:60:in `replaygainAlbum': undefined method `%' for nil:NilClass (NoMethodError)
Traceback (most recent call last):
	2: from /usr/local/lib/rubyripper/encode.rb:86:in `block (2 levels) in startEncoding'
	1: from /usr/local/lib/rubyripper/encode.rb:153:in `encodeTrack'
/usr/local/lib/rubyripper/codecs/main.rb:60:in `replaygainAlbum': undefined method `%' for nil:NilClass (NoMethodError)
```

**Comment by FoilBlue** [comment]
my system:
Used drive     : HL-DT-ST DVDRAM GSA-4167B DL11
Ubuntu 20.04.2 LTS 
Gnome 3.36.8 with gnome-shell
x11
Rip seamed to complete successfully btw

**Comment by FoilBlue** [comment]
Oh!  Meant to say big THANK YOU!!! :D So happy to be still able to use ruby ripper :D. Fav ripper. Spent ages finding it as a teenager.

**Comment by bleskodev** [comment]
Hi, first of all, thanks for your kind words! It is really appreciated.

Concerning the problem you have; can you give me just a bit more information?
What kind of codec you are trying to use (Opus and some other at the same time or only Opus)?
You have activated replaygain for Opus (replaygain for Opus does not exist, but this should issue a warning not cause the crash) or you have activated replaygain for several codecs?
You say that wavegain dependency was missing... you were ripping to wave too?

Thanks!

**Comment by FoilBlue** [comment]
Thank you again :D.

opus and flac. not encoding to wave.
Replay gain settings that seam to be applied to everything by the looks of the config screen, The dropdown/checkbox.

I thought maybe rubyripper does not rip to output formats directly and starts with ripped wave files, then applies replay gain -if option enabled-, then transcoded into other formats. Hence i guessed it mattered if wavegain was not installed.

**Comment by bleskodev** [comment]
OK, I have reproduced your problem. Fix is available if you can get the latest.
It would be great if you could confirm the fix.
Thanks!

**Comment by FoilBlue** [comment]
git pulled and installed Rubyripper version 0.8.0rc3

**Comment by FoilBlue** [comment]
ill test when i got a cd to rip... or later bit busy eek. been thinking of raiding mums cd collection and try something...

**Comment by FoilBlue** [comment]
Oh thank you for your efforts!

**Comment by FoilBlue** [comment]
just did a quick test :). yes it works. Added replygain to the flacs but not the opus encode and didnt crash :). just ripped one track to save time on old already ripped cd.

Thank you again so much! :D

**Comment by bleskodev** [comment]
Cool!
