### ISSUE TITLE
Update Danish Translation

### ISSUE THREAD

**Issue by joedamhan** [bleskodev/rubyripper#641]
[rubyripper.po.tar.gz](https://github.com/bleskodev/rubyripper/files/12474293/rubyripper.po.tar.gz)

an update for master for Danish translation

joe@debianbuster:~/over/andet/rubyripper$ msgfmt --statistics -c -v -o /dev/null rubyripper.po
rubyripper.po: 404 oversatte tekster.
joe@debianbuster:~/over/andet/rubyripper$ 
bye
Joe

**Comment by bleskodev** [comment]
Applied!
Thanks for your work Joe!
